/**
 * Impact Loop Booking — comparison vs Calendly + manual prep.
 */
const calendlyFlow = [
  { label: "Prospect picks slot", actor: "Prospect", auto: true },
  { label: "Calendar invite sent", actor: "System", auto: true },
  { label: "Manual brief writeup", actor: "Founder (45 min)", auto: false },
  { label: "Prospect arrives unprepared", actor: "Prospect", auto: false },
  { label: "Call starts at intro level", actor: "Both", auto: false },
];
const customFlow = [
  { label: "Prospect picks slot", actor: "Prospect", auto: true },
  { label: "Pre-call diagnostic", actor: "Prospect (5 min)", auto: false },
  { label: "Slot re-validated, calendar event created", actor: "System", auto: true },
  { label: "AI brief generated by challenge type", actor: "System", auto: true },
  { label: "Prospect gets pre-call email", actor: "System", auto: true },
  { label: "Founder gets brief 1hr before", actor: "System", auto: true },
  { label: "Call starts at strategic level", actor: "Both", auto: false },
];

export const BookingComparison = () => (
  <div className="bg-secondary border border-border rounded-md p-6 md:p-10 my-10">
    <p className="text-xs font-semibold tracking-[0.3em] uppercase text-accent-deep mb-2">
      Calendly + manual vs custom flow
    </p>
    <h3 className="text-2xl md:text-3xl font-serif font-bold mb-8">
      Two-sided briefing changes where the call starts.
    </h3>

    <div className="grid md:grid-cols-2 gap-6">
      {/* Calendly */}
      <div className="bg-card border border-border rounded-md p-6">
        <div className="flex items-center gap-3 mb-5">
          <span className="px-2 py-1 rounded bg-secondary text-foreground text-xs font-bold uppercase tracking-widest">Before</span>
          <h4 className="font-serif text-xl font-bold">Calendly + manual prep</h4>
        </div>

        <ol className="space-y-2.5">
          {calendlyFlow.map((step, idx) => (
            <li key={idx} className="flex items-start gap-3">
              <span className={`mt-1 w-2 h-2 rounded-full shrink-0 ${step.auto ? "bg-accent" : "bg-muted-foreground"}`} />
              <div>
                <p className="text-sm font-semibold leading-tight">{step.label}</p>
                <p className="text-xs text-muted-foreground mt-0.5">{step.actor}</p>
              </div>
            </li>
          ))}
        </ol>

        <div className="mt-5 pt-4 border-t border-border space-y-1.5">
          <p className="text-xs text-muted-foreground"><strong className="text-foreground">Pre-call prep:</strong> 45 min/call manual</p>
          <p className="text-xs text-muted-foreground"><strong className="text-foreground">Race condition:</strong> possible</p>
          <p className="text-xs text-muted-foreground"><strong className="text-foreground">CRM sync:</strong> manual / forgotten</p>
        </div>
      </div>

      {/* Custom */}
      <div className="bg-foreground text-background rounded-md p-6 border-2 border-accent">
        <div className="flex items-center gap-3 mb-5">
          <span className="px-2 py-1 rounded bg-accent text-foreground text-xs font-bold uppercase tracking-widest">After</span>
          <h4 className="font-serif text-xl font-bold">Custom booking flow</h4>
        </div>

        <ol className="space-y-2.5">
          {customFlow.map((step, idx) => (
            <li key={idx} className="flex items-start gap-3">
              <span className={`mt-1 w-2 h-2 rounded-full shrink-0 ${step.auto ? "bg-accent" : "bg-background/40"}`} />
              <div>
                <p className="text-sm font-semibold leading-tight">{step.label}</p>
                <p className="text-xs opacity-60 mt-0.5">{step.actor}</p>
              </div>
            </li>
          ))}
        </ol>

        <div className="mt-5 pt-4 border-t border-background/15 space-y-1.5">
          <p className="text-xs opacity-80"><strong className="text-accent">Pre-call prep:</strong> 0 min manual (auto-brief)</p>
          <p className="text-xs opacity-80"><strong className="text-accent">Race condition:</strong> eliminated (slot re-validated)</p>
          <p className="text-xs opacity-80"><strong className="text-accent">CRM sync:</strong> automatic on every action</p>
        </div>
      </div>
    </div>
  </div>
);

export default BookingComparison;
